### PR TITLE
Fix indented case in given

### LINKED ISSUE #337: Indented case in given
### Commit of tree-sitter-scala you tested this on

f14629b4d53f72356ce8f6d4ac8c54d21b4e74dd

### A code sample showing the error

~~~scala
given Show[Int] =
  case n => "123"
~~~

### Show the error node

~~~
(compilation_unit [0, 0] - [2, 0]
  (given_definition [0, 0] - [1, 11]
    return_type: (generic_type [0, 6] - [0, 15]
      type: (type_identifier [0, 6] - [0, 10])
      type_arguments: (type_arguments [0, 10] - [0, 15]
        (type_identifier [0, 11] - [0, 14])))
    body: (infix_expression [1, 2] - [1, 11]
      left: (identifier [1, 2] - [1, 6])
      operator: (identifier [1, 7] - [1, 8])
      right: (operator_identifier [1, 9] - [1, 11])))
  (ERROR [1, 12] - [2, 0]))
~~~

### What do you expect the tree to look like

I expect that `case n => "123"` parses as same as in the following code:

~~~scala
{
  case n => "123"
}
~~~

So the correct tree would be similar to this:

~~~
(compilation_unit [0, 0] - [2, 0]
  (given_definition [0, 0] - [1, 11]
    return_type: (generic_type [0, 6] - [0, 15]
      type: (type_identifier [0, 6] - [0, 10])
      type_arguments: (type_arguments [0, 10] - [0, 15]
        (type_identifier [0, 11] - [0, 14])))
    body: (case_clause [1, 2] - [1, 18]
      pattern: (identifier [1, 7] - [1, 8])
      body: (string [1, 12] - [1, 17]))))
~~~

### Where are you experiencing this error?

_No response_

### PR DESCRIPTION
**Pull request by Masynchin**
Fix #337

- Update `given_definition` in `grammar.json`
- Add code sample with given with indented case in `corpus/definitions.txt`
- Update `corpus/definitions.txt` trees:
  - Add tree of the added code sample
  - Update "Inline given (Scala 3)" code sample tree due to PR changes

### CODE REVIEW

**Comment by Masynchin** [comment]
The current tests passed well (except one that I updated accordingly), but I failed to correctly set up smoke test script, so I don't know how this changes affects smoke test numbers

File: grammar.js [hunk 1]
```diff
@@ -589,7 +589,7 @@ module.exports = grammar({
             seq(
               field("return_type", $._annotated_type),
               "=",
-              field("body", $.expression),
+              field("body", $._indentable_expression),
```
Comment (eed3si9n) [inline grammar.js:592]: Thanks @Masynchin!

**Review by eed3si9n — APPROVED** [review]
