### PR TITLE
fix: issue outdents before commas

### LINKED ISSUE #449: Trailing coma after for comprehension in lambda parameter of a function
### Commit of tree-sitter-scala you tested this on

fb999c7

### A code sample showing the error

```scala
object Foo:
  def foo(f: Option[Int] => Option[Int]): Option[Int] = f(None)

  foo(o =>
    for {
      a <- o
    } yield a,
  )
```

### Show the error node

```
...
          (lambda_expression ; [3, 6] - [7, 2]
            parameters: (identifier) ; [3, 6] - [3, 7]
            (indented_block ; [4, 4] - [7, 2]
              (for_expression ; [4, 4] - [6, 13]
                enumerators: (enumerators ; [5, 6] - [6, 4]
                  (enumerator ; [5, 6] - [5, 12]
                    (identifier) ; [5, 6] - [5, 7]
                    (identifier))) ; [5, 11] - [5, 12]
                body: (identifier)) ; [6, 12] - [6, 13]
              (ERROR)))))))) ; [6, 13] - [6, 14]
...
```

### What do you expect the tree to look like

```
          (lambda_expression ; [3, 6] - [7, 2]
            parameters: (identifier) ; [3, 6] - [3, 7]
            (indented_block ; [4, 4] - [7, 2]
              (for_expression ; [4, 4] - [6, 13]
                enumerators: (enumerators ; [5, 6] - [6, 4]
                  (enumerator ; [5, 6] - [5, 12]
                    (identifier) ; [5, 6] - [5, 7]
                    (identifier))) ; [5, 11] - [5, 12]
                body: (identifier))))))))) ; [6, 12] - [6, 13]
```

### Where are you experiencing this error?

nvim-treesitter

### PR DESCRIPTION
**Pull request by susliko**
Fixes #449

Also covers cases with colon arguments in function invocations, e.g.
```scala
foo(
  xs.map: x =>
     x + 1,
  ys
)
```

`lila` has a lot of such code

### CODE REVIEW

File: script/smoke_test.sh [hunk 1]
```diff
@@ -5,8 +5,8 @@
 SCALA_SCALA_LIBRARY_EXPECTED=100
 SCALA_SCALA_COMPILER_EXPECTED=96
 DOTTY_COMPILER_EXPECTED=89
-LILA_MODULES_EXPECTED=92
-SYNTAX_COMPLEXITY_CEILING=1600
+LILA_MODULES_EXPECTED=95
+SYNTAX_COMPLEXITY_CEILING=1950
```
Comment (susliko) [inline script/smoke_test.sh:9]: I was unable to achieve lower ceiling with this change

**Review by eed3si9n — APPROVED** [review]
Thanks!
